#!/usr/bin/env python3
"""Genera SLCC_frasi.csv con un elenco di frasi di esempio per ciascun polo
delle dicotomie SLCC (Shift, Show, Sort, Start, Style).

Il file CSV risultante ha due colonne: "SLCC" (nome della dicotomia/polo,
es. "Arguments Facts") e "frase" (esempio di frase associata).

Le frasi sono basate su quelle già presenti nei file .md di
Human Connection Enginering (HCE)/Corso Persuasione/SLCC, integrate con
varianti coerenti nello stesso stile. Rieseguendo lo script, SLCC_frasi.csv
viene rigenerato da zero (sovrascritto).
"""

import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent / "SLCC_frasi.csv"

DATA = {
    "Arguments Facts": [
        "Voglio prendere in mano la situazione",
        "Voglio toccare con mano",
        "Non vedo bene questa cosa",
        "Se non vedo non ci credo",
        "Chi te l'ha detto?",
        "Fammi vedere i dati",
        "Dimostramelo con i fatti",
        "Mostrami le prove",
        "Voglio verificarlo di persona",
        "Parliamo di cose concrete",
    ],
    "Arguments Intuitions": [
        "Immagino che",
        "Suppongo che",
        "Dovrebbe succedere che",
        "Ho la sensazione che",
        "Mi viene da pensare che",
        "Presumo che",
        "Credo che potrebbe andare così",
        "Il mio istinto mi dice che",
        "Ipotizzo che",
        "Sento che sarà così",
    ],
    "Reference External": [
        "Ho letto",
        "Mi hanno detto",
        "Le recensioni dicono",
        "Tutti fanno così",
        "Gli esperti sostengono che",
        "Si dice in giro che",
        "L'ho visto fare da altri",
        "Cosa ne pensano gli altri?",
        "Mi conviene sentire prima cosa dicono loro",
        "Se lo fanno tutti un motivo ci sarà",
    ],
    "Reference Internal": [
        "Penso",
        "Secondo me",
        "A mio parere",
        "Io la vedo così",
        "Sono convinto che",
        "Per come la penso io",
        "Mi fido del mio giudizio",
        "Decido da solo cosa è giusto",
        "Non mi interessa cosa dicono gli altri",
        "Io so cosa è meglio per me",
    ],
    "Results Best": [
        "Nel migliore dei casi",
        "Se tutto va bene",
        "Il massimo che possiamo ottenere",
        "Pensiamo in grande",
        "Immaginiamo il risultato ideale",
        "Potrebbe andare benissimo",
        "Vediamo il lato positivo",
        "Nella situazione ottimale",
        "Se le cose vanno come spero",
        "Puntiamo al risultato migliore",
    ],
    "Results Worst": [
        "Nel peggiore dei casi",
        "Se va tutto storto",
        "Speriamo non succeda il peggio",
        "E se non funzionasse?",
        "Meglio prepararsi al peggio",
        "Nella situazione più sfortunata",
        "Cosa succede se fallisce?",
        "Mettiamo in conto che vada male",
        "Nel caso più disastroso",
        "Devo pensare a cosa potrebbe andare storto",
    ],
    "Criteria Difference": [
        "Diversamente dall'altro anno",
        "Questo è diverso da quello",
        "Non c'entra niente con l'altro progetto",
        "È tutta un'altra cosa",
        "Cambia completamente rispetto a prima",
        "Non è per niente come l'altra volta",
        "Qui la situazione è opposta",
        "Rispetto a prima, è cambiato tutto",
        "Non ha nulla a che vedere con l'altro caso",
        "È l'esatto contrario di quello che avevamo",
    ],
    "Criteria Similarity": [
        "Un luogo come l'altro anno",
        "Questo è simile a quello",
        "È praticamente la stessa cosa",
        "Ci ricorda molto l'esperienza precedente",
        "Assomiglia a quello che abbiamo già fatto",
        "È in linea con ciò che conosciamo",
        "Stesso discorso di prima",
        "Funziona allo stesso modo di prima",
        "È coerente con quanto visto finora",
        "Ricalca lo stesso schema di sempre",
    ],
    "Information Generic": [
        "Fammi una panoramica",
        "Dimmi un po'",
        "A grandi linee",
        "In generale come funziona?",
        "Dammi un'idea generale",
        "Raccontami un po' di cosa si tratta",
        "Senza scendere nei dettagli",
        "Un riassunto veloce va bene",
        "Dammi il quadro d'insieme",
        "Spiegami sommariamente",
    ],
    "Information Specific": [
        "Dimmi esattamente",
        "Nei dettagli, di cosa si tratta?",
        "Voglio sapere ogni singolo passaggio",
        "Entra nel dettaglio, per favore",
        "Quali sono i numeri precisi?",
        "Spiegami punto per punto",
        "Ho bisogno di tutte le specifiche",
        "Puoi essere più preciso?",
        "Dammi i dettagli tecnici",
        "Che cosa esattamente devo fare?",
    ],
    "Phylosophy How": [
        "Dimmi come si fa",
        "Qual è il procedimento?",
        "Come lo mettiamo in pratica?",
        "Con quali passaggi si arriva al risultato?",
        "Che metodo dobbiamo seguire?",
        "Come funziona nel concreto?",
        "Qual è il modo giusto per farlo?",
        "Mostrami come procedere passo dopo passo",
        "Come si applica in pratica?",
        "Dammi indicazioni operative",
    ],
    "Phylosophy Why": [
        "Perché dovrei farlo?",
        "Qual è il senso di tutto questo?",
        "Voglio capire il motivo",
        "A cosa serve davvero?",
        "Qual è lo scopo di questa scelta?",
        "Perché è importante?",
        "Cosa c'è dietro questa decisione?",
        "Qual è il valore di tutto ciò?",
        "Prima di agire, voglio capire il perché",
        "Che significato ha per me?",
    ],
    "Consistency Alignment": [
        "Mangiare bene è una cosa importante",
        "Questo rispecchia esattamente ciò in cui credo",
        "È coerente con i miei valori",
        "Va tutto nella direzione giusta per me",
        "Mi ritrovo pienamente in questo",
        "È proprio quello in cui credo",
        "Fa parte di ciò che considero giusto",
        "Sento che è la cosa corretta da fare",
        "Rispetta i principi a cui tengo",
        "È in linea con il mio modo di vedere le cose",
    ],
    "Consistency Conflict": [
        "Lavorare senza mangiare è intollerabile",
        "Questo va contro tutto ciò in cui credo",
        "Non è coerente con i miei valori",
        "Mi crea un forte conflitto interiore",
        "Non riesco ad accettarlo, va contro i miei principi",
        "È in contraddizione con quello che penso giusto",
        "Non posso tollerare una cosa simile",
        "Sento che è sbagliato rispetto a ciò che sono",
        "Stride con il mio modo di vedere le cose",
        "Non rispetta ciò che per me è fondamentale",
    ],
    "Depth Appearance": [
        "Non sto molto bene",
        "Sono soddisfatto",
        "Sembra tutto a posto",
        "Va tutto bene, grazie",
        "Oggi sono un po' stanco",
        "Sono contento del risultato",
        "Mi sento tranquillo",
        "Va tutto come previsto",
        "Sono nervoso",
        "Sto passando una brutta giornata",
    ],
    "Depth Essence": [
        "Non sto bene perché ho avuto un trauma per questo",
        "Sono soddisfatto perché finalmente ho raggiunto un obiettivo che inseguivo da anni",
        "Sono stanco perché non dormo bene da quando è successo quel fatto",
        "Sono nervoso perché temo di deludere le aspettative di mio padre",
        "Sono contento perché questo risultato conferma il mio valore",
        "Mi sento tranquillo perché ho finalmente chiuso un capitolo doloroso",
        "Sto male perché mi sento in colpa per una scelta passata",
        "Va tutto come previsto perché ho lavorato sulle mie paure",
        "Sono felice perché ho superato una ferita che mi portavo dietro da tempo",
        "Reagisco così perché in fondo temo di non essere abbastanza",
    ],
    "Moment Future": [
        "Domani",
        "Faremo",
        "Proiettiamo",
        "Il prossimo passo sarà",
        "Guardiamo avanti",
        "Nei prossimi mesi",
        "Quello che verrà",
        "Puntiamo a diventare",
        "Tra qualche anno vorrei",
        "Pensiamo a dove vogliamo arrivare",
    ],
    "Moment Past": [
        "Quando le cose erano come una volta",
        "Mi ricordo che facevamo sempre",
        "Come una volta",
        "Ai vecchi tempi",
        "Ripensando a quello che è successo",
        "Ricordo ancora quando",
        "Un tempo si faceva così",
        "Guardando indietro",
        "Mi rifaccio a quello che abbiamo già vissuto",
        "Era già successo in passato",
    ],
    "Motivation Gain": [
        "Ottenere/raggiungere un obiettivo",
        "Voglio conquistare questo risultato",
        "Punto a guadagnarci qualcosa",
        "Mi motiva l'idea di crescere",
        "Voglio arrivare più in alto",
        "Cerco un vantaggio in più",
        "Voglio migliorare la mia situazione",
        "Mi spinge il desiderio di ottenere di più",
        "Voglio raggiungere il massimo risultato possibile",
        "Sono attratto dall'opportunità di guadagnare",
    ],
    "Motivation Loss": [
        "Voglio evitare questo problema",
        "Voglio allontanarmi da questa situazione",
        "Non voglio più soffrire così",
        "Devo scappare da questo rischio",
        "Voglio evitare di perdere quello che ho",
        "Mi muovo per non ritrovarmi in difficoltà",
        "Non voglio più vivere questo disagio",
        "Preferisco prevenire piuttosto che rischiare",
        "Voglio togliermi da questo fastidio",
        "Mi spinge la paura di perdere qualcosa",
    ],
    "Operation Options": [
        "Iniziamo e poi vediamo",
        "Potremmo fare..",
        "Strada facendo vediamo",
        "Vediamo come va e ci adattiamo",
        "Non serve un piano rigido",
        "Proviamo diverse strade",
        "Ci lasciamo aperte più possibilità",
        "Decidiamo man mano",
        "Improvvisiamo un po'",
        "Aggiustiamo il tiro strada facendo",
    ],
    "Operation Procedure": [
        "Dimmi esattamente come fare",
        "Per prima cosa",
        "Quando abbiamo finito facciamo..",
        "Seguiamo i passaggi nell'ordine giusto",
        "C'è una procedura precisa da rispettare",
        "Facciamo un elenco delle cose da fare",
        "Prima questo, poi quello",
        "Serve uno schema preciso",
        "Andiamo con ordine, punto per punto",
        "Meglio seguire una lista dettagliata",
    ],
    "Overture Act": [
        "Partiamo subito",
        "Iniziamo oggi stesso",
        "Facciamolo adesso",
        "Non perdiamo altro tempo",
        "Muoviamoci subito",
        "Agiamo prima di pensarci troppo",
        "Cominciamo immediatamente",
        "Buttiamoci e vediamo cosa succede",
        "Meglio fare che stare fermi",
        "Diamoci da fare subito",
    ],
    "Overture Reflect": [
        "Voglio ragionarci bene",
        "Devo rifletterci su",
        "Ho bisogno del tempo per decidere",
        "Fammi pensare prima di rispondere",
        "Meglio non affrettare le cose",
        "Prendiamoci il tempo necessario",
        "Voglio valutare bene i pro e i contro",
        "Non voglio decidere di getto",
        "Lasciami dormirci sopra",
        "Prima di agire voglio essere sicuro",
    ],
    "Changes Innovator": [
        "Vorrei rivoluzionare tutto",
        "Ho bisogno di qualcosa di nuovo",
        "Proviamo un approccio diverso",
        "Basta con le solite cose",
        "Mi piace sperimentare novità",
        "Cambiamo completamente strategia",
        "Cerchiamo una soluzione originale",
        "Rompiamo gli schemi",
        "Voglio innovare il modo in cui lo facciamo",
        "Perché non provare qualcosa di mai fatto prima?",
    ],
    "Changes Traditional": [
        "Squadra che vince non si cambia!",
        "Preferisco il sentiero battuto",
        "Meglio non rischiare con novità inutili",
        "Continuiamo a fare come sempre",
        "Se ha sempre funzionato, perché cambiarlo?",
        "Restiamo sul collaudato",
        "Non serve stravolgere tutto",
        "Manteniamo le nostre abitudini",
        "Meglio la sicurezza del solito metodo",
        "Le cose vanno bene così come sono",
    ],
    "Focus Distracted": [
        "Pensare fuori dagli schemi",
        "Esplorare prima tutte le possibilità",
        "Guardiamo un po' tutto prima di scegliere",
        "Mi piace saltare da un argomento all'altro",
        "Teniamo aperte più piste insieme",
        "Vediamo diverse opzioni in parallelo",
        "Non voglio fermarmi su un solo aspetto",
        "Passiamo in rassegna varie idee",
        "Mi distraggo facilmente su nuovi spunti",
        "Preferisco avere una visione ampia su tutto",
    ],
    "Focus Immersive": [
        "Restiamo su questo punto",
        "Approfondiamo questo argomento",
        "Concentriamoci solo su questo per ora",
        "Non passiamo oltre finché non è chiaro",
        "Voglio finire una cosa prima di iniziarne un'altra",
        "Mi immergo completamente in questo dettaglio",
        "Fermiamoci qui e analizziamolo a fondo",
        "Un argomento alla volta, per favore",
        "Diamo priorità a questo singolo aspetto",
        "Voglio scavare a fondo su questo punto",
    ],
    "Subordination Commanders": [
        "Fai come dico io",
        "Decido io per tutti",
        "Prendo io il comando",
        "Da qui in poi guido io",
        "Ci penso io a organizzare tutto",
        "Seguite le mie indicazioni",
        "Assegno io i compiti",
        "La responsabilità finale è mia",
        "Voglio essere io a decidere come procedere",
        "Mi prendo io la guida del gruppo",
    ],
    "Subordination Workers": [
        "Dimmi cosa devo fare",
        "Seguo le istruzioni",
        "Faccio quello che mi viene chiesto",
        "Aspetto indicazioni prima di agire",
        "Mi adeguo a quello che decide il gruppo",
        "Preferisco eseguire piuttosto che decidere",
        "Ditemi come devo comportarmi",
        "Mi affido a chi guida",
        "Va bene, faccio come stabilito",
        "Aspetto ordini chiari prima di procedere",
    ],
}


def main():
    with OUT.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["SLCC", "frase"])
        for slcc, frasi in DATA.items():
            for frase in frasi:
                writer.writerow([slcc, frase])

    print(f"Scritte {sum(len(v) for v in DATA.values())} righe in {OUT}")


if __name__ == "__main__":
    main()
